version: "3"
services:
  goenv:
    container_name: "go_environment"
    build:
      context: .
      dockerfile: ./app/docker/Dockerfile
    tty: true
    volumes:
      - ./app:/go/src/app

  migrate:
    container_name: "flyway_environment"
    image: amazoncorretto:11
    tty: true
    working_dir: /flyway
    volumes:
      - ./flyway:/flyway
    depends_on:
            - database

  db:
    container_name: mysql_container
    image: mysql:8.0
    environment:
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: go_database
      MYSQL_USER: go_test
      MYSQL_PASSWORD: p@55w0rd
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306

volumes:
  db-data:
    driver: local
